"use client";

import React, { useState, useEffect, useRef } from "react";
import GeneratedWireflow from "@/components/GeneratedWireflow";
import FileTreeExplorer from "@/components/FileTreeExplorer";

type FileItem = {
  path: string;
  name: string;
  isDirectory?: boolean;
  content?: string;
  children?: FileItem[];
};

type ChatMessage = {
  role: "user" | "assistant";
  content: string;
  model?: string;
};

export default function Home() {
  const AVAILABLE_MODELS = [
    { provider: "groq", model: "llama-3.3-70b-versatile", label: "Llama 3.3 70B" },
    { provider: "groq", model: "mixtral-8x7b-32768", label: "Mixtral 8x7B" },
    { provider: "groq", model: "deepseek-r1-distill-llama-70b", label: "DeepSeek R1" },
    { provider: "groq", model: "qwen-2.5-72b-instruct", label: "Qwen 2.5 72B" },
  ];

  // Navigation & UI Layout State
  const [activeSidebarTab, setActiveSidebarTab] = useState<"Explorer" | "Search" | "Git" | "Settings">("Explorer");
  const [activeWorkspaceTab, setActiveWorkspaceTab] = useState<string>("Wireflow");
  const [sidebarCollapsed, setSidebarCollapsed] = useState<boolean>(false);
  const [terminalCollapsed, setTerminalCollapsed] = useState<boolean>(false);

  // Input & Prompting State
  const [prompt, setPrompt] = useState<string>("");
  const [modelSelection, setModelSelection] = useState<{provider: string; model: string; label: string}>({
    provider: "groq",
    model: "llama-3.3-70b-versatile",
    label: "Llama 3.3 70B",
  });
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);

  // Generation Flow States
  const [wireflow, setWireflow] = useState<any>(null);
  const [architecture, setArchitecture] = useState<any>(null);
  const [files, setFiles] = useState<any[]>([]); // current workspace files shown in left explorer
  const [generatedFiles, setGeneratedFiles] = useState<any[] | null>(null); // files generated by LLM
  
  // Editor States
  const [selectedFile, setSelectedFile] = useState<FileItem | null>(null);
  const [openTabs, setOpenTabs] = useState<FileItem[]>([]);
  const [isEditing, setIsEditing] = useState<boolean>(false);
  const [editContent, setEditContent] = useState<string>("");

  // Modals & User Input Action Forms
  const [showChangesModal, setShowChangesModal] = useState<boolean>(false);
  const [changeRequest, setChangeRequest] = useState<string>("");
  const [showStackChanges, setShowStackChanges] = useState<boolean>(false);
  const [stackChangeRequest, setStackChangeRequest] = useState<string>("");

  // Terminal & Compiler Loop States
  const [terminalOutput, setTerminalOutput] = useState<string>("");
  const [compilerStatus, setCompilerStatus] = useState<"idle" | "installing" | "compiling" | "healing" | "success" | "failed">("idle");
  const [loading, setLoading] = useState<boolean>(false);
  const [projectName, setProjectName] = useState<string>("pepul-desktop");

  // Git & Search Workspace States
  const [gitStatus, setGitStatus] = useState<{ branch: string; modifiedFiles: { path: string; status: string }[] }>({
    branch: "main",
    modifiedFiles: [],
  });
  const [searchQuery, setSearchQuery] = useState<string>("");
  const [searchResults, setSearchResults] = useState<{ filePath: string; lineNumber: number; lineContent: string }[]>([]);

  // Refs for scrolling
  const terminalEndRef = useRef<HTMLDivElement>(null);
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Load Workspace Root initially
  useEffect(() => {
    loadWorkspaceFiles();
    loadGitStatus();
  }, []);

  // Auto-scroll elements
  useEffect(() => {
    terminalEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [terminalOutput]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [chatMessages]);

  // Handle Electron logs and status streams
  useEffect(() => {
    if (window.electronAPI) {
      window.electronAPI.onTerminalLog((log: string) => {
        setTerminalOutput((prev) => prev + log);
      });

      window.electronAPI.onBuildStatus((status: any) => {
        setCompilerStatus(status);
        if (status === "success" || status === "failed" || status === "idle") {
          loadWorkspaceFiles();
          loadGitStatus();
        }
      });
    }
  }, []);

  const loadWorkspaceFiles = async () => {
    if (window.electronAPI) {
      const workspaceTree = await window.electronAPI.getWorkspaceFiles();
      setFiles(workspaceTree || []);
    }
  };

  const loadGitStatus = async () => {
    if (window.electronAPI) {
      const status = await window.electronAPI.getGitStatus() as { branch?: string; modifiedFiles?: { path: string; status: string }[] } | undefined;
      setGitStatus({
        branch: status?.branch || "main",
        modifiedFiles: status?.modifiedFiles || [],
      });
    }
  };

  // Safe JSON extraction
  const parseJson = (raw: string) => {
    const start = raw.indexOf("{");
    const end = raw.lastIndexOf("}");
    if (start === -1 || end === -1) {
      throw new Error("Invalid JSON response");
    }
    return JSON.parse(raw.slice(start, end + 1));
  };

  // STEP 1: Prompt submission and Wireflow Generation
  const handlePromptSubmit = async () => {
    if (!prompt.trim() || loading) return;

    const userMsg = prompt;
    setPrompt("");
    setChatMessages((prev) => [...prev, { role: "user", content: userMsg }]);
    setLoading(true);

    try {
      setChatMessages((prev) => [
        ...prev,
        { role: "assistant", content: "📐 Constructing applications screens and flow diagram. Please wait...", model: modelSelection.label },
      ]);

      const response = await window.electronAPI.generateWireflow(userMsg);
      if (!response.success) {
        throw new Error(response.error);
      }

      const raw = response.data || "";
      const parsedWireflow = parseJson(raw);

      if (parsedWireflow._error) {
        setChatMessages((prev) => [
          ...prev.slice(0, -1),
          {
            role: "assistant",
            content: `⚠️ ${parsedWireflow._error}`,
            model: modelSelection.label,
          },
        ]);
        setWireflow(null);
      } else {
        setWireflow(parsedWireflow);
        setProjectName(parsedWireflow.projectName || "generated-app");
        setActiveWorkspaceTab("Wireflow");
        setChatMessages((prev) => [
          ...prev.slice(0, -1),
          {
            role: "assistant",
            content: `📐 Generated the **Wireflow Diagram** for your idea: **"${parsedWireflow.projectName}"**. Please review the visual screen layout in the center canvas.`,
            model: modelSelection.label,
          },
        ]);
      }
    } catch (err: any) {
      setChatMessages((prev) => [
        ...prev.slice(0, -1),
        { role: "assistant", content: `❌ Error generating wireflow: ${err.message}`, model: modelSelection.label },
      ]);
    } finally {
      setLoading(false);
    }
  };

  // Wireflow Changes Form
  const submitWireflowChanges = async () => {
    if (!changeRequest.trim() || loading) return;
    setShowChangesModal(false);
    setLoading(true);

    const updatedPrompt = `${prompt}\n\nAdditional Wireflow Changes requested:\n${changeRequest}`;
    setChangeRequest("");

    setChatMessages((prev) => [
      ...prev,
      { role: "assistant", content: "🔄 Regenerating wireflow with requested layout alterations..." },
    ]);

    try {
      const response = await window.electronAPI.generateWireflow(updatedPrompt);
      if (!response.success) throw new Error(response.error);

      const parsedWireflow = parseJson(response.data || "");
      setWireflow(parsedWireflow);

      setChatMessages((prev) => [
        ...prev.slice(0, -1),
        { role: "assistant", content: "📐 Wireflow updated! Check the revised center diagram." },
      ]);
    } catch (e: any) {
      setChatMessages((prev) => [
        ...prev.slice(0, -1),
        { role: "assistant", content: `❌ Revision failed: ${e.message}` },
      ]);
    } finally {
      setLoading(false);
    }
  };

  // STEP 2: Approve Wireflow & Generate Stack Architecture
  const handleApproveWireflow = async () => {
    if (loading) return;
    setLoading(true);
    setChatMessages((prev) => [
      ...prev,
      { role: "assistant", content: "🏗 Defining the technology stack components and database APIs..." },
    ]);

    try {
      const res = await window.electronAPI.generateArchitecture(wireflow);
      if (!res.success) throw new Error(res.error);

      const archData = parseJson(res.data || "");
      setArchitecture(archData);

      // Redirect to Architecture tab
      setActiveWorkspaceTab("Architecture");

      setChatMessages((prev) => [
        ...prev.slice(0, -1),
        {
          role: "assistant",
          content: "🏗 Technology Stack Architecture is ready. You can inspect the suggested Frontend, Backend, Database layer, and system API routes. Approve or customize the Stack settings.",
        },
      ]);
    } catch (e: any) {
      setChatMessages((prev) => [
        ...prev.slice(0, -1),
        { role: "assistant", content: `❌ Stack generation error: ${e.message}` },
      ]);
    } finally {
      setLoading(false);
    }
  };

  // Architecture Modifications Form
  const submitStackChanges = async () => {
    if (!stackChangeRequest.trim() || loading) return;
    setShowStackChanges(false);
    setLoading(true);

    setChatMessages((prev) => [
      ...prev,
      { role: "assistant", content: `🔄 Modifying Stack with request: "${stackChangeRequest}"...` },
    ]);

    const complexPrompt = `
Original Wireflow: ${JSON.stringify(wireflow)}
Requested Tech Stack Revisions: ${stackChangeRequest}
`;
    setStackChangeRequest("");

    try {
      const res = await window.electronAPI.generateArchitecture(complexPrompt);
      if (!res.success) throw new Error(res.error);

      const archData = parseJson(res.data || "");
      setArchitecture(archData);

      setChatMessages((prev) => [
        ...prev.slice(0, -1),
        { role: "assistant", content: "🏗 Tech stack customized successfully!" },
      ]);
    } catch (e: any) {
      setChatMessages((prev) => [
        ...prev.slice(0, -1),
        { role: "assistant", content: `❌ Customization failed: ${e.message}` },
      ]);
    } finally {
      setLoading(false);
    }
  };

  // STEP 3: Accept Stack & Generate Source Code Files
  const handleAcceptArchitecture = () => {
    // Redirect to Files tab
    setActiveWorkspaceTab("Files");
    setChatMessages((prev) => [
      ...prev,
      { role: "assistant", content: "📂 Stack locked. You are now in the project workspace section. Click **Generate Code** to write the source files." },
    ]);
  };

  const handleGenerateCode = async () => {
    if (loading) return;
    setLoading(true);
    setChatMessages((prev) => [
      ...prev,
      { role: "assistant", content: "💻 Generating complete source files, Express endpoints, and script structures..." },
    ]);

    try {
      // Fetch mock directories structure first
      const foldersRes = await window.electronAPI.generateFileStructure(architecture);
      let directories = ["src", "src/routes", "database"];
      try {
        const parsedFolders = parseJson(foldersRes.data || "");
        directories = parsedFolders.folders || directories;
      } catch (e) {}

      const codeRes = await window.electronAPI.generateCode(architecture, wireflow, directories);
      if (!codeRes.success) throw new Error(codeRes.error);

      const parsedCode = parseJson(codeRes.data || "");
      setGeneratedFiles(parsedCode.files || []);

      setChatMessages((prev) => [
        ...prev.slice(0, -1),
        {
          role: "assistant",
          content: "💻 Code files generated! Now starting local compilation and testing via terminal. Watch the self-healing runner process logs.",
        },
      ]);

      // Automatically trigger Build loop
      startSelfHealingProcess(parsedCode.files || []);
    } catch (e: any) {
      setChatMessages((prev) => [
        ...prev.slice(0, -1),
        { role: "assistant", content: `❌ Code generation failed: ${e.message}` },
      ]);
    } finally {
      setLoading(false);
    }
  };

  // Terminal Compilation Spawner
  const startSelfHealingProcess = async (projectFiles: any[]) => {
    setTerminalOutput("");
    setTerminalCollapsed(false); // Make sure terminal is open to see logs!
    try {
      await window.electronAPI.startBuildLoop(projectName, projectFiles, architecture);
    } catch (e: any) {
      setTerminalOutput((prev) => prev + `[Antigravity Error] ${e.message}\n`);
    }
  };

  // Save edits of selected file in Editor tab
  const handleSaveFile = async () => {
    if (!selectedFile) return;
    if (window.electronAPI) {
      const res = await window.electronAPI.writeFile(selectedFile.path, editContent);
      if (res.success) {
        setIsEditing(false);
        selectedFile.content = editContent;
        // Re-read file list and update status
        loadWorkspaceFiles();
        loadGitStatus();
      } else {
        alert("Save failed: " + res.error);
      }
    }
  };

  // Sidebar File Selection
  const handleSelectFile = async (file: FileItem) => {
    if (file.isDirectory) return;
    try {
      const res = await window.electronAPI.readFile(file.path);
      if (res.success) {
        const itemWithContent = { ...file, content: res.content };
        setSelectedFile(itemWithContent);
        setEditContent(res.content || "");
        setIsEditing(false);
        
        // Add to tabs if not already present
        if (!openTabs.some((t) => t.path === file.path)) {
          setOpenTabs((prev) => [...prev, itemWithContent]);
        }
        
        // Set tab focus to 'Files' workspace tab
        setActiveWorkspaceTab("Files");
      }
    } catch (e: any) {
      console.error(e);
    }
  };

  const closeEditorTab = (tabPath: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const remaining = openTabs.filter((t) => t.path !== tabPath);
    setOpenTabs(remaining);
    if (selectedFile?.path === tabPath) {
      if (remaining.length > 0) {
        const last = remaining[remaining.length - 1];
        setSelectedFile(last);
        setEditContent(last.content || "");
      } else {
        setSelectedFile(null);
      }
    }
  };

  // Workspace File Text Search
  const handleSearchSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchQuery.trim() || !window.electronAPI) return;
    const results = await window.electronAPI.searchFiles(searchQuery);
    setSearchResults(results || []);
  };

  // Agent Chat Block Code apply feature
  const applyAgentCodeBlock = async (content: string) => {
    if (!selectedFile) {
      alert("Please open a file in the editor first to apply this code block.");
      return;
    }
    // Attempt to parse out just code or replace entire file
    setEditContent(content);
    setIsEditing(true);
    alert(`Code applied to ${selectedFile.name} editor. Press Save to write modifications to disk.`);
  };

  // Helper function to extract code blocks from agent response text
  const renderAgentMarkdown = (text: string) => {
    const parts = text.split("```");
    return parts.map((part, index) => {
      // Odd indices are code blocks
      if (index % 2 === 1) {
        const firstNewline = part.indexOf("\n");
        const lang = part.substring(0, firstNewline).trim();
        const code = part.substring(firstNewline + 1).trim();

        return (
          <div key={index} className="my-3 border border-zinc-800 rounded-lg overflow-hidden bg-[#0d1117] font-mono text-xs text-zinc-300">
            <div className="bg-[#161b22] px-3 py-1.5 flex items-center justify-between border-b border-zinc-800 text-[10px] text-zinc-500 uppercase font-bold select-none">
              <span>{lang || "code"}</span>
              <button
                onClick={() => applyAgentCodeBlock(code)}
                className="bg-sky-950/70 hover:bg-sky-900 border border-sky-850 hover:border-sky-800 text-sky-400 px-2 py-0.5 rounded transition-all"
              >
                Apply Code
              </button>
            </div>
            <pre className="p-3 overflow-x-auto whitespace-pre">{code}</pre>
          </div>
        );
      }

      // Even indices are standard markdown lines
      return (
        <p key={index} className="whitespace-pre-wrap leading-relaxed text-zinc-300 text-xs mb-1">
          {part}
        </p>
      );
    });
  };

  // Simple syntax highlighter for preview mode
  const highlightCode = (code: string) => {
    if (!code) return "";
    let escaped = code
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");

    const keywords = /\b(const|let|var|function|return|import|export|from|class|extends|new|if|else|for|while|async|await|try|catch|default|module|exports|require|switch|case|break)\b/g;
    escaped = escaped.replace(keywords, '<span class="text-pink-500 font-bold">$1</span>');

    escaped = escaped.replace(/(["'`])(.*?)\1/g, '<span class="text-emerald-400">$1$2$1</span>');
    escaped = escaped.replace(/(\/\/.*)/g, '<span class="text-zinc-500">$1</span>');
    escaped = escaped.replace(/(\/\*[\s\S]*?\*\/)/g, '<span class="text-zinc-500">$1</span>');

    return escaped;
  };

  return (
    <main className="h-screen bg-[#0d1117] text-white flex flex-col font-sans select-none overflow-hidden">
      
      {/* MAIN LAYOUT WRAPPER */}
      <div className="flex-1 flex min-h-0 relative">
        
        {/* COLUMN 1: VERTICAL ACTIVITY BAR (VS Code Style) */}
        <div className="w-14 bg-[#090d12] border-r border-[#21262d] flex flex-col items-center py-4 justify-between select-none">
          <div className="flex flex-col gap-6 items-center w-full">
            
            {/* Explorer Icon */}
            <button
              onClick={() => {
                setActiveSidebarTab("Explorer");
                setSidebarCollapsed(false);
              }}
              className={`p-2.5 rounded-lg transition-all relative group ${
                activeSidebarTab === "Explorer" && !sidebarCollapsed ? "text-sky-500 bg-[#161b22]" : "text-zinc-500 hover:text-zinc-300"
              }`}
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
              </svg>
              {activeSidebarTab === "Explorer" && !sidebarCollapsed && (
                <div className="absolute left-0 top-1 bottom-1 w-1 bg-sky-500 rounded-r" />
              )}
            </button>

            {/* Search Icon */}
            <button
              onClick={() => {
                setActiveSidebarTab("Search");
                setSidebarCollapsed(false);
              }}
              className={`p-2.5 rounded-lg transition-all relative group ${
                activeSidebarTab === "Search" && !sidebarCollapsed ? "text-sky-500 bg-[#161b22]" : "text-zinc-500 hover:text-zinc-300"
              }`}
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
              {activeSidebarTab === "Search" && !sidebarCollapsed && (
                <div className="absolute left-0 top-1 bottom-1 w-1 bg-sky-500 rounded-r" />
              )}
            </button>

            {/* Git Icon */}
            <button
              onClick={() => {
                setActiveSidebarTab("Git");
                setSidebarCollapsed(false);
              }}
              className={`p-2.5 rounded-lg transition-all relative group ${
                activeSidebarTab === "Git" && !sidebarCollapsed ? "text-sky-500 bg-[#161b22]" : "text-zinc-500 hover:text-zinc-300"
              }`}
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M8 7a3 3 0 100-6 3 3 0 000 6zM8 7v7a4 4 0 00.26 1.44m0 0a4 4 0 001.07 1.45m0 0a3 3 0 106.33-1.6c0-.98-.4-1.9-1.07-2.56M12 10a4 4 0 00-4 4" />
              </svg>
              {gitStatus.modifiedFiles.length > 0 && (
                <span className="absolute top-1 right-1 bg-sky-600 text-white font-bold text-[8px] w-4 h-4 rounded-full flex items-center justify-center scale-90 border border-[#090d12]">
                  {gitStatus.modifiedFiles.length}
                </span>
              )}
              {activeSidebarTab === "Git" && !sidebarCollapsed && (
                <div className="absolute left-0 top-1 bottom-1 w-1 bg-sky-500 rounded-r" />
              )}
            </button>
          </div>

          <div className="flex flex-col gap-6 items-center w-full">
            {/* Settings Icon */}
            <button
              onClick={() => {
                setActiveSidebarTab("Settings");
                setSidebarCollapsed(false);
              }}
              className={`p-2.5 rounded-lg transition-all relative group ${
                activeSidebarTab === "Settings" && !sidebarCollapsed ? "text-sky-500 bg-[#161b22]" : "text-zinc-500 hover:text-zinc-300"
              }`}
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
            </button>

            {/* Profile Avatar */}
            <div className="w-6 h-6 rounded-full bg-gradient-to-tr from-sky-600 to-indigo-600 border border-zinc-700 flex items-center justify-center text-[10px] font-bold text-white uppercase cursor-pointer">
              U
            </div>
          </div>
        </div>

        {/* COLUMN 2: SIDEBAR PANEL (Collapsible Explorer) */}
        {!sidebarCollapsed && (
          <div className="w-64 bg-[#161b22] border-r border-[#21262d] flex flex-col min-h-0 select-none">
            
            {/* Explorer Header */}
            {activeSidebarTab === "Explorer" && (
              <div className="flex-1 flex flex-col min-h-0">
                <div className="p-3 border-b border-[#21262d] flex items-center justify-between text-xs font-semibold text-zinc-400 uppercase tracking-wider">
                  <span>Explorer</span>
                  <div className="flex items-center gap-2 text-zinc-500 hover:text-zinc-300 cursor-pointer">
                    <span onClick={loadWorkspaceFiles} title="Refresh workspace">⟳</span>
                    <span>•••</span>
                  </div>
                </div>

                <div className="p-2 border-b border-[#21262d] bg-[#0d1117]/30 flex items-center gap-1.5 text-xs text-zinc-200 font-bold truncate">
                  <span className="text-yellow-600">📁</span>
                  <span>{projectName}</span>
                </div>

                <div className="flex-1 overflow-y-auto">
                  <FileTreeExplorer
                    files={files}
                    onSelectFile={handleSelectFile}
                    selectedFile={selectedFile}
                    gitModifiedFiles={gitStatus.modifiedFiles.map((f) => f.path)}
                  />
                </div>

                {/* Accordions */}
                <div className="border-t border-[#21262d] p-2 bg-[#090d12]/30 text-xs text-zinc-500 flex items-center justify-between font-bold uppercase cursor-pointer hover:bg-[#161b22]">
                  <span>Outline</span>
                  <span>▼</span>
                </div>
                <div className="border-t border-[#21262d] p-2 bg-[#090d12]/30 text-xs text-zinc-500 flex items-center justify-between font-bold uppercase cursor-pointer hover:bg-[#161b22]">
                  <span>Timeline</span>
                  <span>▼</span>
                </div>
              </div>
            )}

            {/* Search Tab */}
            {activeSidebarTab === "Search" && (
              <div className="flex-1 flex flex-col min-h-0 p-4">
                <div className="text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-3">
                  Search in Workspace
                </div>
                <form onSubmit={handleSearchSubmit} className="flex gap-2 mb-4">
                  <input
                    type="text"
                    placeholder="Search text..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="flex-1 bg-[#0d1117] border border-[#21262d] rounded-md px-3 py-1.5 text-xs font-mono text-white focus:outline-none focus:border-sky-500"
                  />
                  <button type="submit" className="bg-sky-600 hover:bg-sky-500 text-white rounded px-3 text-xs font-bold transition-all">
                    Go
                  </button>
                </form>

                <div className="flex-1 overflow-y-auto space-y-2">
                  <div className="text-[10px] text-zinc-500 font-bold uppercase select-none">
                    Results ({searchResults.length})
                  </div>
                  {searchResults.map((res, index) => (
                    <div
                      key={index}
                      onClick={() => handleSelectFile({ path: res.filePath, name: res.filePath.split("/").pop() || "" })}
                      className="p-2 border border-[#21262d] rounded bg-[#0d1117] hover:border-zinc-700 cursor-pointer font-mono text-[10px] leading-relaxed transition-all"
                    >
                      <div className="text-sky-400 font-bold truncate">{res.filePath}:{res.lineNumber}</div>
                      <div className="text-zinc-500 italic truncate">"{res.lineContent}"</div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Source Control Git Tab */}
            {activeSidebarTab === "Git" && (
              <div className="flex-1 flex flex-col min-h-0 p-4">
                <div className="text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-2">
                  Source Control
                </div>
                <div className="text-[10px] text-zinc-500 font-mono mb-4 flex items-center gap-1.5 select-none">
                  <span>Branch:</span>
                  <span className="bg-[#0d1117] px-2 py-0.5 border border-zinc-800 text-sky-400 rounded">
                    {gitStatus.branch}
                  </span>
                </div>

                <div className="flex-1 overflow-y-auto space-y-2.5">
                  <div className="text-[10px] text-zinc-500 font-bold uppercase select-none">
                    Unstaged Changes ({gitStatus.modifiedFiles.length})
                  </div>
                  
                  {gitStatus.modifiedFiles.length === 0 ? (
                    <div className="text-xs text-zinc-600 font-mono italic select-none">
                      No modified files detected
                    </div>
                  ) : (
                    <div className="space-y-1">
                      {gitStatus.modifiedFiles.map((file, idx) => (
                        <div
                          key={idx}
                          onClick={() => handleSelectFile({ path: file.path, name: file.path.split("/").pop() || "" })}
                          className="flex items-center justify-between p-1.5 rounded hover:bg-[#0d1117]/80 group cursor-pointer text-xs font-mono"
                        >
                          <span className="truncate text-amber-500/90">{file.path}</span>
                          <span className="text-[10px] text-amber-500 font-bold shrink-0">{file.status}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {/* Commit Form */}
                <div className="pt-4 border-t border-[#21262d]">
                  <textarea
                    placeholder="Commit message..."
                    className="w-full bg-[#0d1117] border border-[#21262d] rounded p-2 text-xs font-mono focus:outline-none focus:border-zinc-700 resize-none h-16 text-zinc-200"
                  />
                  <button className="w-full bg-zinc-800 hover:bg-zinc-700 font-bold py-1.5 rounded mt-2 text-xs transition-all">
                    Commit Changes
                  </button>
                </div>
              </div>
            )}

            {/* Settings Tab */}
            {activeSidebarTab === "Settings" && (
              <div className="flex-1 flex flex-col min-h-0 p-4 space-y-4">
                <div className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">
                  IDE Settings
                </div>
                
                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] text-zinc-500 font-bold uppercase">Workspace Root</label>
                  <div className="bg-[#0d1117] border border-[#21262d] rounded-lg p-2 font-mono text-[10px] leading-relaxed break-all select-all">
                    {activeWorkspaceTab === "Files" && files.length > 0
                      ? "data/..." 
                      : "/Users/ironman/project/pepul/pepul-desktop"}
                  </div>
                </div>

                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] text-zinc-500 font-bold uppercase">LLM Provider</label>
                  <span className="text-xs text-zinc-300 font-medium">Groq Llama Cloud API</span>
                </div>
              </div>
            )}

          </div>
        )}

        {/* COLUMN 3: CENTER AREA (Workspace, Tabs, Editor, Terminal) */}
        <div className="flex-1 flex flex-col min-w-0 bg-[#0d1117]">
          
          {/* TAB BAR FOR CENTER WORKSPACE */}
          <div className="flex border-b border-[#21262d] bg-[#161b22] select-none h-11 items-center justify-between pr-4">
            <div className="flex h-full">
              {[
                { id: "Wireflow", name: "📐 Wireflow" },
                { id: "Architecture", name: "🏗 Architecture" },
                { id: "Files", name: "📁 Files" },
              ].map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setActiveWorkspaceTab(tab.id)}
                  className={`px-5 h-full border-r border-[#21262d] text-xs font-semibold transition-all relative ${
                    activeWorkspaceTab === tab.id
                      ? "bg-[#0d1117] text-white"
                      : "text-zinc-500 hover:text-zinc-300 hover:bg-[#161b22]/40"
                  }`}
                >
                  <span>{tab.name}</span>
                  {activeWorkspaceTab === tab.id && (
                    <div className="absolute top-0 left-0 right-0 h-[3px] bg-sky-500" />
                  )}
                </button>
              ))}
            </div>

            {/* Collapse sidebar button */}
            <button
              onClick={() => setSidebarCollapsed(!sidebarCollapsed)}
              className="text-zinc-500 hover:text-zinc-300 p-1.5 rounded transition-all"
              title="Toggle Sidebar"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M4 6h16M4 12h16M4 18h16" />
              </svg>
            </button>
          </div>

          {/* MAIN CANVAS CONTENT CONTAINER */}
          <div className="flex-1 overflow-hidden relative flex flex-col min-h-0">
            
            {/* WIREFLOW CANVAS */}
            {activeWorkspaceTab === "Wireflow" && (
              <div className="w-full h-full flex flex-col relative min-h-0">
                {wireflow ? (
                  <div className="flex-1 relative min-h-0 bg-[#030712]">
                    <GeneratedWireflow wireflow={wireflow} />

                    {/* WIREFLOW FLOW VERIFICATION CONTROLS */}
                    <div className="absolute bottom-4 left-4 right-4 z-10 bg-[#161b22]/95 border border-[#30363d] p-3 rounded-lg flex items-center justify-between shadow-2xl backdrop-blur-md">
                      <div className="text-[10px] text-zinc-400 flex items-center gap-1.5 select-none font-mono">
                        <span className="w-2.5 h-2.5 rounded-full bg-sky-500 animate-pulse" />
                        <span>Interactive Wireflow. Approve to configure stack.</span>
                      </div>

                      <div className="flex gap-2">
                        <button
                          onClick={() => setShowChangesModal(true)}
                          className="bg-zinc-800 hover:bg-zinc-700 text-xs font-bold px-3 py-1.5 rounded-md border border-[#30363d] transition-all"
                        >
                          Request Diagram Changes
                        </button>
                        <button
                          onClick={handleApproveWireflow}
                          disabled={loading}
                          className="bg-sky-600 hover:bg-sky-500 disabled:opacity-50 text-xs font-bold px-4 py-1.5 rounded-md text-white transition-all shadow-lg shadow-sky-950/20"
                        >
                          {loading ? "Generating stack..." : "Approve Diagram & Build Stack"}
                        </button>
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="flex-1 flex flex-col items-center justify-center text-center p-8 bg-[#0d1117] select-none">
                    <div className="w-16 h-16 rounded-full bg-[#161b22] border border-[#21262d] flex items-center justify-center text-2xl mb-4 shadow-xl">
                      📐
                    </div>
                    <h2 className="text-sm font-bold text-zinc-300">No Wireflow Diagram</h2>
                    <p className="text-xs text-zinc-500 mt-1 max-w-sm leading-relaxed">
                      Enter your application features or layout flow in the right Agent Chat panel and click send to compile the screens.
                    </p>
                  </div>
                )}
              </div>
            )}

            {/* ARCHITECTURE CANVAS */}
            {activeWorkspaceTab === "Architecture" && (
              <div className="w-full h-full flex flex-col p-6 overflow-y-auto relative bg-[#0d1117]">
                {!architecture ? (
                  <div className="flex-1 flex flex-col items-center justify-center text-center p-8 select-none">
                    <div className="w-16 h-16 rounded-full bg-[#161b22] border border-[#21262d] flex items-center justify-center text-2xl mb-4 shadow-xl">
                      🏗
                    </div>
                    <h2 className="text-sm font-bold text-zinc-300">Architecture Offline</h2>
                    <p className="text-xs text-zinc-500 mt-1 max-w-sm leading-relaxed">
                      Define and approve your wireflow diagram first to fetch stack options automatically.
                    </p>
                  </div>
                ) : (
                  <div className="max-w-3xl space-y-6 pb-24">
                    <div>
                      <h2 className="text-lg font-bold text-zinc-100 font-mono">System Stack Selection</h2>
                      <p className="text-xs text-zinc-500 mt-0.5">The tech architecture defined for the project.</p>
                    </div>

                    <div className="grid grid-cols-2 gap-4">
                      {[
                        { label: "Frontend Framework", val: architecture.frontend, icon: "💻" },
                        { label: "Backend Core", val: architecture.backend, icon: "⚙️" },
                        { label: "Database Layer", val: architecture.database, icon: "💾" },
                        { label: "Authentication System", val: architecture.auth, icon: "🔒" },
                      ].map((item, index) => (
                        <div key={index} className="bg-[#161b22] border border-[#21262d] rounded-xl p-4 flex items-start gap-3">
                          <span className="text-lg select-none">{item.icon}</span>
                          <div className="min-w-0">
                            <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-wide block">{item.label}</span>
                            <span className="text-xs text-zinc-200 font-medium block mt-0.5 truncate">{item.val}</span>
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* API List */}
                    <div className="bg-[#161b22] border border-[#21262d] rounded-xl p-4">
                      <div className="text-[10px] font-bold text-zinc-500 uppercase tracking-wide mb-3 select-none">
                        Exposed API Endpoints
                      </div>
                      <div className="space-y-2 max-h-56 overflow-y-auto pr-2">
                        {architecture.apis?.map((api: any, idx: number) => {
                          const name = typeof api === "string" ? api : (api.name || "API");
                          const endpoint = typeof api === "string" ? "/api/v1" : (api.endpoint || "/api");
                          const method = typeof api === "string" ? "GET" : (api.methods ? (Array.isArray(api.methods) ? api.methods.join(", ") : api.methods) : "GET");
                          
                          return (
                            <div key={idx} className="border-b border-[#21262d]/50 pb-2 last:border-none last:pb-0 flex items-center justify-between text-xs font-mono">
                              <span className="font-semibold text-zinc-300">{name}</span>
                              <div className="flex items-center gap-2">
                                <span className="bg-[#0d1117] text-zinc-400 border border-zinc-800 px-2 py-0.5 rounded text-[10px]">
                                  {endpoint}
                                </span>
                                <span className="bg-sky-950/70 border border-sky-900 text-sky-400 px-2 py-0.5 rounded text-[9px] font-bold">
                                  {method}
                                </span>
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    </div>

                    {/* ARCHITECTURE ACTIONS */}
                    <div className="border-t border-[#21262d] pt-6 flex items-center justify-between gap-4">
                      <button
                        onClick={() => setShowStackChanges(true)}
                        className="bg-zinc-800 hover:bg-zinc-700 text-xs font-bold px-4 py-2 rounded-md border border-[#30363d] transition-all"
                      >
                        Modify Stack Components
                      </button>

                      <button
                        onClick={handleAcceptArchitecture}
                        className="bg-sky-600 hover:bg-sky-500 text-xs font-bold px-5 py-2 rounded-md text-white transition-all shadow-lg shadow-sky-950/20"
                      >
                        Accept Stack & Proceed to Files
                      </button>
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* FILES CANVAS & EDITOR */}
            {activeWorkspaceTab === "Files" && (
              <div className="w-full h-full flex flex-col overflow-hidden min-h-0 bg-[#0d1117]">
                
                {/* Editor Tabs bar */}
                {openTabs.length > 0 && (
                  <div className="bg-[#161b22]/60 border-b border-[#21262d] flex items-center h-9 pr-3">
                    <div className="flex h-full flex-1 overflow-x-auto min-w-0">
                      {openTabs.map((tab) => (
                        <div
                          key={tab.path}
                          onClick={() => handleSelectFile(tab)}
                          className={`flex items-center gap-2 px-3 h-full border-r border-[#21262d] cursor-pointer text-xs font-mono transition-all select-none relative ${
                            selectedFile?.path === tab.path ? "bg-[#0d1117] text-white" : "text-zinc-500 hover:text-zinc-300"
                          }`}
                        >
                          <span>{tab.name}</span>
                          <button
                            onClick={(e) => closeEditorTab(tab.path, e)}
                            className="w-3 h-3 hover:bg-zinc-800 rounded-full flex items-center justify-center text-[8px] font-bold text-zinc-500 hover:text-zinc-300"
                          >
                            ×
                          </button>
                          {selectedFile?.path === tab.path && (
                            <div className="absolute bottom-0 left-0 right-0 h-[2px] bg-sky-500" />
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                <div className="flex-1 overflow-hidden min-h-0 flex flex-col relative">
                  {selectedFile ? (
                    <div className="flex-1 flex flex-col overflow-hidden min-h-0">
                      
                      {/* Editor Actions bar */}
                      <div className="bg-[#161b22]/30 border-b border-[#21262d] px-4 py-1.5 flex items-center justify-between text-[10px] text-zinc-500 select-none">
                        <span className="font-mono truncate">{selectedFile.path}</span>
                        <div className="flex items-center gap-2">
                          {isEditing ? (
                            <>
                              <button
                                onClick={() => setIsEditing(false)}
                                className="hover:text-zinc-300 font-bold px-2 py-0.5 bg-zinc-800 rounded transition-all"
                              >
                                Cancel
                              </button>
                              <button
                                onClick={handleSaveFile}
                                className="text-sky-400 font-bold px-2.5 py-0.5 bg-sky-950/60 border border-sky-900 rounded hover:bg-sky-900 transition-all"
                              >
                                Save File (Cmd+S)
                              </button>
                            </>
                          ) : (
                            <button
                              onClick={() => {
                                setEditContent(selectedFile.content || "");
                                setIsEditing(true);
                              }}
                              className="text-sky-400 hover:text-sky-300 font-bold px-2.5 py-0.5 bg-sky-950/60 border border-sky-900 rounded transition-all"
                            >
                              Edit Code
                            </button>
                          )}
                        </div>
                      </div>

                      {/* Code Area */}
                      <div className="flex-1 overflow-y-auto flex min-h-0 relative font-mono text-xs leading-relaxed text-zinc-300 bg-[#0d1117]">
                        
                        {/* Line number gutter */}
                        <div className="w-10 bg-[#0d1117] border-r border-[#21262d]/50 pr-2.5 py-4 text-right text-zinc-600 select-none text-[10px]">
                          {(isEditing ? editContent : selectedFile.content || "")
                            .split("\n")
                            .map((_, i) => (
                              <div key={i}>{i + 1}</div>
                            ))}
                        </div>

                        {/* Code Display or Editor Textarea */}
                        <div className="flex-1 p-4 relative min-h-0 overflow-x-auto">
                          {isEditing ? (
                            <textarea
                              value={editContent}
                              onChange={(e) => setEditContent(e.target.value)}
                              onKeyDown={(e) => {
                                // Cmd+S or Ctrl+S listener
                                if ((e.metaKey || e.ctrlKey) && e.key === "s") {
                                  e.preventDefault();
                                  handleSaveFile();
                                }
                              }}
                              className="w-full h-full bg-transparent text-zinc-300 font-mono text-xs outline-none border-none resize-none focus:ring-0 whitespace-pre"
                            />
                          ) : (
                            <pre
                              className="whitespace-pre overflow-x-auto"
                              dangerouslySetInnerHTML={{
                                __html: highlightCode(selectedFile.content || ""),
                              }}
                            />
                          )}
                        </div>
                      </div>

                    </div>
                  ) : (
                    <div className="flex-1 flex flex-col items-center justify-center text-center p-8 bg-[#0d1117] select-none">
                      
                      {/* Visual placeholder matching Antigravity IDE welcome view */}
                      {!generatedFiles ? (
                        <div className="flex flex-col items-center justify-center">
                          {/* Stylized 'A' logo */}
                          <div className="w-20 h-20 mb-4 text-white flex items-center justify-center filter drop-shadow-[0_0_15px_rgba(56,189,248,0.15)] animate-pulse">
                            <svg className="w-16 h-16" viewBox="0 0 100 100" fill="none" stroke="currentColor" strokeWidth="6">
                              <path d="M50 15L15 85H30L50 45L70 85H85L50 15Z" strokeLinejoin="round" />
                              <path d="M37 70H63" />
                            </svg>
                          </div>
                          <h1 className="text-xl font-bold font-mono tracking-wide text-zinc-100">Antigravity IDE</h1>
                          <p className="text-xs text-zinc-500 mt-1.5 font-mono uppercase tracking-widest">Code with Agent</p>
                          <div className="mt-6 flex items-center gap-1">
                            <kbd className="bg-zinc-800 border border-zinc-700 px-2 py-1 rounded text-xs font-bold text-zinc-400 select-none shadow">⌘</kbd>
                            <kbd className="bg-zinc-800 border border-zinc-700 px-2 py-1 rounded text-xs font-bold text-zinc-400 select-none shadow">L</kbd>
                          </div>

                          <button
                            onClick={handleGenerateCode}
                            disabled={loading || !architecture}
                            className="bg-sky-600 hover:bg-sky-500 disabled:opacity-50 text-xs font-bold px-6 py-2.5 rounded-lg text-white mt-10 transition-all shadow-lg shadow-sky-950/40 border border-sky-500/20"
                          >
                            {loading ? "Generating Application structure..." : "⚡ Generate Source Files"}
                          </button>
                        </div>
                      ) : (
                        <div className="flex flex-col items-center justify-center">
                          <div className="text-3xl mb-3">📄</div>
                          <h2 className="text-sm font-bold text-zinc-300">Select a File to Preview</h2>
                          <p className="text-xs text-zinc-500 mt-1 max-w-sm leading-relaxed">
                            Click a file from the explorer in the left sidebar to preview and edit its code.
                          </p>
                        </div>
                      )}

                    </div>
                  )}
                </div>

              </div>
            )}

            {/* LIVE TERMINAL CONTAINER (Collapsible at bottom) */}
            {!terminalCollapsed && (
              <div className="h-48 border-t border-[#21262d] bg-[#040404] flex flex-col min-h-0 select-none font-mono">
                
                {/* Terminal Header Tabs */}
                <div className="bg-[#0c0c0c] border-b border-[#21262d] px-4 h-9 flex items-center justify-between text-[10px] text-zinc-500 select-none font-bold uppercase">
                  <div className="flex gap-4">
                    <span className="text-sky-400 border-b-2 border-sky-500 pb-2 pt-1">Terminal</span>
                    <span className="hover:text-zinc-300 cursor-pointer pb-2 pt-1">Problems</span>
                    <span className="hover:text-zinc-300 cursor-pointer pb-2 pt-1">Output</span>
                  </div>
                  
                  <div className="flex items-center gap-3">
                    {/* Status dot */}
                    <div className="flex items-center gap-1.5 font-bold uppercase text-[9px]">
                      {compilerStatus === "installing" && (
                        <>
                          <span className="w-2 h-2 rounded-full bg-yellow-500 animate-ping" />
                          <span className="text-yellow-500">Installing Modules...</span>
                        </>
                      )}
                      {compilerStatus === "compiling" && (
                        <>
                          <span className="w-2 h-2 rounded-full bg-blue-500 animate-pulse" />
                          <span className="text-blue-500">Compiling Project...</span>
                        </>
                      )}
                      {compilerStatus === "healing" && (
                        <>
                          <span className="w-2 h-2 rounded-full bg-amber-500 animate-ping" />
                          <span className="text-amber-500 font-bold animate-pulse">Self-Healing Code...</span>
                        </>
                      )}
                      {compilerStatus === "success" && (
                        <>
                          <span className="w-2 h-2 rounded-full bg-emerald-500" />
                          <span className="text-emerald-500">Working Successfully</span>
                        </>
                      )}
                      {compilerStatus === "failed" && (
                        <>
                          <span className="w-2 h-2 rounded-full bg-rose-500" />
                          <span className="text-rose-500 font-bold">Failed to compile</span>
                        </>
                      )}
                    </div>
                    <button
                      onClick={() => setTerminalCollapsed(true)}
                      className="hover:text-zinc-300 text-xs text-zinc-500 shrink-0 font-bold"
                    >
                      _
                    </button>
                  </div>
                </div>

                {/* Terminal Console Logs */}
                <div className="flex-1 p-4 overflow-y-auto font-mono text-[10px] leading-relaxed text-zinc-300 select-text whitespace-pre-wrap selection:bg-zinc-800">
                  {terminalOutput ? (
                    <div>
                      {terminalOutput}
                      <div ref={terminalEndRef} />
                    </div>
                  ) : (
                    <div className="text-zinc-600 italic">Terminal output idle. Start build loops to stream verification checks...</div>
                  )}
                </div>
              </div>
            )}

          </div>

          {/* Open Terminal Bar if collapsed */}
          {terminalCollapsed && (
            <div
              onClick={() => setTerminalCollapsed(false)}
              className="bg-[#0c0c0c] border-t border-[#21262d] px-4 h-8 flex items-center justify-between text-[9px] text-zinc-500 font-bold uppercase cursor-pointer hover:bg-zinc-900 transition-all select-none"
            >
              <span>💻 Open Terminal Log Console</span>
              <div className="flex items-center gap-1.5 font-bold uppercase">
                {compilerStatus !== "idle" && (
                  <span className="w-1.5 h-1.5 rounded-full bg-sky-500 animate-ping" />
                )}
                <span>{compilerStatus}</span>
              </div>
            </div>
          )}

        </div>

        {/* COLUMN 4: RIGHT PANEL (Agent Chat Interface) */}
        <div className="w-96 bg-[#161b22] border-l border-[#21262d] flex flex-col min-h-0">
          
          {/* Agent Header */}
          <div className="p-4 border-b border-[#21262d] flex items-center justify-between font-semibold select-none">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-sky-500 animate-pulse" />
              <span className="text-sm text-zinc-200">Agent</span>
            </div>
            
            <div className="flex items-center gap-3 text-zinc-500 hover:text-zinc-300 text-xs cursor-pointer">
              <span
                onClick={() => setChatMessages([])}
                title="Reset conversation"
              >
                +
              </span>
              <span>🕒</span>
              <span>•••</span>
              <span className="text-[10px]">✕</span>
            </div>
          </div>

          {/* Chat Bubble List */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4 select-text">
            {chatMessages.map((msg, index) => (
              <div
                key={index}
                className={`flex flex-col max-w-[85%] ${msg.role === "user" ? "ml-auto" : "mr-auto"}`}
              >
                {/* Sender Title */}
                <span className="text-[9px] font-bold text-zinc-500 uppercase tracking-wide mb-1 px-1">
                  {msg.role === "user" ? "You" : "Antigravity Agent"}
                </span>

                {/* Bubble content */}
                <div
                  className={`p-3 rounded-2xl border ${
                    msg.role === "user"
                      ? "bg-sky-950/30 border-sky-900/60 text-zinc-200 rounded-tr-none"
                      : "bg-[#0d1117] border-[#21262d] text-zinc-300 rounded-tl-none"
                  }`}
                >
                  {msg.role === "user" ? (
                    <p className="text-xs whitespace-pre-wrap leading-relaxed select-text">{msg.content}</p>
                  ) : (
                    <div>
                      {renderAgentMarkdown(msg.content)}
                      {msg.model && (
                        <div className="text-[8px] text-zinc-600 font-mono mt-2 select-none uppercase tracking-widest text-right">
                          model: {msg.model}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              </div>
            ))}
            <div ref={chatEndRef} />
          </div>

          {/* Chat input box */}
          <div className="p-4 border-t border-[#21262d] bg-[#161b22]">
            <div className="bg-[#0d1117] border border-[#21262d] rounded-2xl p-3 flex flex-col gap-2 focus-within:border-sky-600 transition-all select-none">
              
              {/* Context Label */}
              <div className="text-[9px] text-zinc-500 font-bold uppercase tracking-wider font-mono truncate select-none">
                📁 {projectName}
              </div>

              {/* Text Input */}
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="i need a exact clone for ..."
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    handlePromptSubmit();
                  }
                }}
                className="w-full bg-transparent text-xs font-mono text-zinc-200 outline-none border-none resize-none focus:ring-0 h-16"
              />

              {/* Toolbar */}
              <div className="flex items-center justify-between border-t border-[#21262d]/50 pt-2 select-none">
                <div className="flex items-center gap-2.5">
                  <button className="text-zinc-500 hover:text-zinc-300 text-sm" title="Add file/context font">
                    +
                  </button>
                  
                  {/* Model Dropdown */}
                  <select
                    value={modelSelection.label}
                    onChange={(e) => {
                      const selected = AVAILABLE_MODELS.find(m => m.label === e.target.value);
                      if (selected) {
                        setModelSelection(selected);
                        window.electronAPI?.setAIModel({
                          provider: selected.provider,
                          model: selected.model,
                          domain: "chat",
                        }).catch(() => {});
                      }
                    }}
                    className="bg-transparent text-[10px] text-zinc-400 font-bold border-none outline-none focus:ring-0 cursor-pointer font-mono"
                  >
                    {AVAILABLE_MODELS.map(m => (
                      <option key={`${m.provider}-${m.model}`} value={m.label}>
                        [{m.provider}] {m.label}
                      </option>
                    ))}
                  </select>
                </div>

                <div className="flex items-center gap-2">
                  <button className="text-zinc-500 hover:text-zinc-300 text-sm" title="Voice dictation">
                    🎙
                  </button>
                  <button
                    onClick={handlePromptSubmit}
                    disabled={loading || !prompt.trim()}
                    className={`w-6 h-6 rounded-full flex items-center justify-center text-white transition-all shadow-md ${
                      prompt.trim() ? "bg-sky-600 hover:bg-sky-500 cursor-pointer scale-100" : "bg-zinc-800 opacity-50 scale-95"
                    }`}
                  >
                    →
                  </button>
                </div>
              </div>

            </div>

            <div className="text-[8px] text-zinc-500 text-center select-none mt-2 font-mono uppercase tracking-widest">
              AI may make mistakes. Double-check all generated code.
            </div>
          </div>

        </div>

      </div>

      {/* BOTTOM STATUS BAR */}
      <div className="h-6 bg-[#090d12] border-t border-[#21262d] px-4 flex items-center justify-between text-[10px] text-zinc-500 select-none">
        
        {/* Left indicators */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1 bg-sky-950/80 text-sky-400 font-bold px-2 py-0.5 border border-sky-900 rounded font-mono select-none">
            <span>⎇</span>
            <span>{gitStatus.branch}*</span>
          </div>
          <div className="flex items-center gap-1 text-zinc-400 font-mono">
            <span>⟳ Sync</span>
          </div>
          <div className="flex items-center gap-1.5 text-zinc-400 font-mono ml-2">
            <span className="text-red-500 font-bold">⊗</span>
            <span>0</span>
            <span className="text-yellow-500 font-bold">⚠</span>
            <span>0</span>
          </div>
        </div>

        {/* Right indicators */}
        <div className="flex items-center gap-4 text-zinc-400 font-mono">
          <span>UTF-8</span>
          <span>TypeScript</span>
          <span className="hover:text-zinc-200 cursor-pointer">Antigravity - Settings</span>
          <span className="hover:text-zinc-200 cursor-pointer" title="Notifications">🔔</span>
        </div>

      </div>

      {/* MODAL: WIREFLOW REQUEST CHANGES */}
      {showChangesModal && (
        <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 p-4 animate-fadeIn">
          <div className="bg-[#161b22] border border-[#21262d] rounded-xl p-5 w-full max-w-lg shadow-2xl relative">
            <h3 className="text-sm font-bold text-zinc-100 font-mono">Request Diagram Flow changes</h3>
            <p className="text-[10px] text-zinc-500 mt-1 select-none">Describe custom revisions to incorporate in screens or flow mapping.</p>
            
            <textarea
              placeholder="e.g. Add product review screens, allow guest access before login..."
              value={changeRequest}
              onChange={(e) => setChangeRequest(e.target.value)}
              className="w-full bg-[#0d1117] border border-[#21262d] rounded-lg p-3 text-xs font-mono mt-3 h-32 focus:outline-none focus:border-sky-500 resize-none text-zinc-200"
            />

            <div className="flex justify-end gap-2 mt-4 select-none">
              <button
                onClick={() => setShowChangesModal(false)}
                className="bg-zinc-800 hover:bg-zinc-700 text-xs font-bold px-3.5 py-1.5 rounded-md border border-[#30363d] transition-all"
              >
                Cancel
              </button>
              <button
                onClick={submitWireflowChanges}
                className="bg-sky-600 hover:bg-sky-500 text-xs font-bold px-4 py-1.5 rounded-md text-white transition-all shadow-md shadow-sky-950/10"
              >
                Update Diagram
              </button>
            </div>
          </div>
        </div>
      )}

      {/* MODAL: ARCHITECTURE STACK CHANGES */}
      {showStackChanges && (
        <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 p-4 animate-fadeIn">
          <div className="bg-[#161b22] border border-[#21262d] rounded-xl p-5 w-full max-w-lg shadow-2xl relative">
            <h3 className="text-sm font-bold text-zinc-100 font-mono">Request Technology Stack changes</h3>
            <p className="text-[10px] text-zinc-500 mt-1 select-none">Enter updates (e.g. use specific database, change libraries or auth setup).</p>
            
            <textarea
              placeholder="e.g. Use PostgreSQL and Prisma ORM, use JWT based auth cookies..."
              value={stackChangeRequest}
              onChange={(e) => setStackChangeRequest(e.target.value)}
              className="w-full bg-[#0d1117] border border-[#21262d] rounded-lg p-3 text-xs font-mono mt-3 h-32 focus:outline-none focus:border-sky-500 resize-none text-zinc-200"
            />

            <div className="flex justify-end gap-2 mt-4 select-none">
              <button
                onClick={() => setShowStackChanges(false)}
                className="bg-zinc-800 hover:bg-zinc-700 text-xs font-bold px-3.5 py-1.5 rounded-md border border-[#30363d] transition-all"
              >
                Cancel
              </button>
              <button
                onClick={submitStackChanges}
                className="bg-sky-600 hover:bg-sky-500 text-xs font-bold px-4 py-1.5 rounded-md text-white transition-all shadow-md shadow-sky-950/10"
              >
                Update Stack
              </button>
            </div>
          </div>
        </div>
      )}

    </main>
  );
}
